### ISSUE TITLE
Using `allowUploadBuffering` implies bad file size

### ISSUE THREAD

**Issue by matschik** [qgustavor/mega#101]
**Describe the bug**
I'm using `allowUploadBuffering` because I don't know the final file size.
But I can't make it work even with a simple example.

```
  Error: Specified data size does not match: 672 !== 0
      at Pumpify.<anonymous> (/node_modules/.pnpm/megajs@1.0.3/node_modules/megajs/dist/main.node-es.mjs:1693:30)
      at Pumpify.emit (node:events:539:35)
      at endReadableNT (/node_modules/.pnpm/readable-stream@3.6.0/node_modules/readable-stream/lib/_stream_readable.js:1094:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**To Reproduce**

Using Node v17.9.0

```js
import { Storage } from 'megajs';
import fs from "fs";

const storage = await new Storage({
    email: "xxx",
    password: "xxx",
}).ready;

const uploadStream = storage.upload({
    name: "package.json",
    allowUploadBuffering: true
});

const readStream = fs.createReadStream("package.json");
readStream.pipe(uploadStream);

uploadStream.on("complete", async (file) => {
    console.log({ file });
    await storage.close();
});

uploadStream.on("error", async (err) => {
    console.log({ err });
    await storage.close();
});
```

**Expected behavior**
The error dot not appear. It must upload the file with success with the right file size using `allowUploadBuffering`

Thanks a lot for maintaining this library. It's wonderful ! <3

**Comment by qgustavor** [comment]
I added a test case to check that to test/storage.test.mjs and it failed. I will fix this issue then release a patch release.

**Comment by qgustavor** [comment]
Can you test the code from here? https://github.com/qgustavor/mega/pull/102

**Comment by matschik** [comment]
It's working perfectly with #102 !!
You are so reactive  ⚡ ! Thank you ❤️
