### ISSUE TITLE
Error: ENOENT (-9): Object (typically, node or user) not found. Wrong password?

### ISSUE THREAD

**Issue by Automized** [qgustavor/mega#111]
Hello, when I attempt to import a file like this **https://mega.nz/folder/R751mQRK#BmDmGaQbcTz-TKT0xt6U4g/file/crw2yRaZ** it throws this error

```Error: ENOENT (-9): Object (typically, node or user) not found. Wrong password?```

I am logged into the account, I can see my storage files etc.

Here is my code:

```js
const { Storage } = require('megajs');


(async function () {
    const storage = await new Storage({
        email: '{email_is_here}',
        password: 'passyword'
    }).ready

    console.log(storage.root.children) //checking to see if i am logged in

    let folder = await storage.mkdir('folder_automized_test')
    await folder.importFile('https://mega.nz/folder/R751mQRK#BmDmGaQbcTz-TKT0xt6U4g/file/crw2yRaZ')
}()).catch(error => {
    console.error(error)
    process.exit(1)
})

**Comment by Automized** [comment]
All good, thank you anyway :)

**Comment by RealAlphabet** [comment]
Does it happen if you do.
```JS
    const storage = await new Storage({
        email: '{email_is_here}',
        password: 'passyword'
    }, () => {}).ready
```

... Instead of ...

```JS
    const storage = await new Storage({
        email: '{email_is_here}',
        password: 'passyword'
    }).ready
```

It solved the problem for me.

**Comment by qgustavor** [comment]
@RealAlphabet Why would adding a empty callback solves it? [Look this](https://github.com/qgustavor/mega/blob/cf77660067e065aaa6e93b3e0b07bddcf5dedf33/lib/storage.mjs#L9-L30): the condition in 12 is always false in both examples then the condition in line 21 creates a callback in case one is not already defined, then line 30 calls the promise handling code. I'm missing something?

**Comment by RealAlphabet** [comment]
I think it would be interesting to drastically change the way this all works. Properly construct the "Storage" object and then have to explicitly call login which is asynchronous.

**Comment by qgustavor** [comment]
I wish I could fix all of this: having Storage work like this is just because backyards compatibility with [tonistiigi's mega](https://github.com/tonistiigi/mega) and older versions. I was planning a complete rewrite for V2 but I'm not in the mood for that right now. Fell free to send a pull request.

**Comment by qgustavor** [comment]
Can you check if this pre-release fixes this issue? https://www.npmjs.com/package/megajs/v/1.1.1-next.3

**Comment by qgustavor** [comment]
More than one week passed and no one commented so I will consider this issue fixed.
