### ISSUE TITLE
Cannot login in browser

### ISSUE THREAD

**Issue by pidtuner** [qgustavor/mega#122]
**Describe the bug**

Thank you for this library and specially for the great docs.
Sadly, with a minimal configuration, and loading from CDN, cannot login in browser

**To Reproduce**

```html
<script src="https://unpkg.com/megajs@1/dist/main.browser-umd.js"></script>
```

```js
let storage = await new mega.Storage({
	email: 'my_account@mega.co.nz',
	password: 'my_password',
	userAgent: null
}).ready;
```

**Expected behavior**
To login, but instead got the error:
```
TypeError: Failed to execute 'importKey' on 'SubtleCrypto': The provided value cannot be converted to a sequence.
```

**Additional context**
![image](https://user-images.githubusercontent.com/43546068/194120322-3b3a3d20-3a00-42a8-a880-627846f32de0.png)

**Comment by qgustavor** [comment]
That's [this line in the source](https://github.com/qgustavor/mega/blob/330cd35270be6aadd59c07d2a3944f65c5d4092d/browser/aes.mjs#L35). The `password` argument is a Buffer [as defined here](https://github.com/qgustavor/mega/blob/330cd35270be6aadd59c07d2a3944f65c5d4092d/lib/storage.mjs#L93). `window.crypto.subtle.importKey` [expects a `Uint8Array`](https://github.com/diafygi/webcrypto-examples/#pbkdf2---importkey). IIRC Buffers should be instances of `Uint8Array` so it should not be an issue.

Maybe your browser implementation expects pure `Uint8Array` objects and do not allow using the `Buffer` object. [Here is a test case for that](https://codepen.io/qgustavor/pen/VwxBBKJ?editors=0010). I tested Firefox/105 and Chrome/106 with success.

**Comment by pidtuner** [comment]
According to [the docs](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey), this fixes it:
```javascript
    function Dn(t, e, r) {
        let n = p.Buffer.from(e.s, "base64")
          , i = 1e5
          , o = "SHA-512";
        window.crypto.subtle.importKey(
                "raw", 
                t, 
                "PBKDF2", // NOTE : string
                !1, 
                ["deriveKey", "deriveBits"] // NOTE : array and add "deriveBits"
        ).then(a=>window.crypto.subtle.deriveBits({
            name: "PBKDF2",
            salt: n,
            iterations: i,
            hash: {
                name: o
            }
        }, a, 256)).then(a=>{
            r(null, p.Buffer.from(a))
        }
        ).catch(r)
    }
```
I wish I knew Typescript to make you a PR

**Comment by qgustavor** [comment]
The source is in JavaScript: https://github.com/qgustavor/mega/blob/330cd35270be6aadd59c07d2a3944f65c5d4092d/browser/aes.mjs#L35
