### ISSUE TITLE
Non-descript error on creating storage

### ISSUE THREAD

**Issue by TsukiyomiSachiko** [qgustavor/mega#143]
**Describe the bug**
Trying to create the storage object by logging in to mega throws a non-descript error. Error could possibly be related to me having 2fa enabled on the account

**To Reproduce**

Run this code in Node 18.12.1 

main.ts
```js
import * as dotenv from 'dotenv';
dotenv.config();

import { Storage } from "megajs";

;(async function() {
    const storage = await new Storage({
        email: process.env["EMAIL"] || "",
        password: process.env["PASS"] || ""
    }).ready

    const file = await storage.upload('hello-world.txt', 'Hello world!').complete
    console.log("File was uploaded", file);
}()).catch((error) => {
    console.error(error);
    process.exit(1);
})
```
If it matters, my password is 18 characters long

Error thrown is the following

```
Error
    at {PROJECT_LOCATION}\node_modules\megajs\dist\main.node-cjs.js:889:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior**
Storage object to be created, and the dummy file to be uploaded to Mega without throwing an error

**Additional context**
Application is run with ts-node to prevent the need to compile typescript into javascript before every run manually/using scripts

**Comment by qgustavor** [comment]
Sorry, I understand that your situation but in order to be fair with everyone I'll have to close the issue due to this: https://github.com/qgustavor/mega/discussions/138
