### ISSUE TITLE
Typescript cannot find CDN modules

### ISSUE THREAD

**Issue by ccmoralesj** [qgustavor/mega#160]
**Describe the bug**
I'm trying to run megajs library but I'm getting a Typescript error saying it can't find CDN modules. It only happens with 4 CDNs but not with the global one:

1. 'https://cdn.deno.land/std/versions/0.125.0/raw/node/_stream.d.ts' 
2. https://cdn.deno.land/std/versions/0.125.0/raw/node/_events.d.ts'
3. 'https://cdn.deno.land/std/versions/0.125.0/raw/node/http.ts'
4. 'https://cdn.deno.land/std/versions/0.125.0/raw/node/https.ts'

GLOBAL doesn't throw an error
import 'https://cdn.deno.land/std/versions/0.125.0/raw/node/global.ts'

This is an example of the errors
![image](https://github.com/qgustavor/mega/assets/5986739/57375af5-c930-4f49-b95d-403adf828380)

**To Reproduce**

I'm running this with Node 20.0.0 npm 9.8.0 in a Ubuntu 22.04 environment. I'm just trying to start the project using megajs

**Expected behavior**
The project starts and I can use megajs as expected

**Comment by qgustavor** [comment]
https://github.com/qgustavor/mega/discussions/138

**Comment by qgustavor** [comment]
Since you didn't have time to read the warning in the issue template I guess you don't have time to send a PR fixing this issue. Well, if you have time just send a PR, you don't need to open an issue. Since I'm not a Typescript user fixing this is not a priority to me.
