### ISSUE TITLE
Invalid or expired user session, please relogin

### ISSUE THREAD

**Issue by JoelSParker** [qgustavor/mega#50]
When looping over multiple files I am getting "Invalid or expired user session, please relogin" after about 6 files.

**Comment by qgustavor** [comment]
Can you detail what steps you did or post a minimal code example where this issue happens?

During the last week I uploaded thousands of files to MEGA without issues. I just tried uploading some files and there was no issue (on the library side, in the other hand my computer is extremely slow due some hardware issue I'm trying to fix now).

By "looping over multiple files" are you trying to upload (ou download) those in parallel or serial?

**Comment by JoelSParker** [comment]
I am trying to download multiple files from an array of Mega links ($links).

After about 6 I start getting a consistent error of "Invalid or expired user session, please relogin"

`links.forEach(function(fileUrl) {
    let file = mega.file(fileUrl)

    file.loadAttributes((error, file) => {
        console.log(fileUrl)
        console.log(error)
        console.log(file)
    })
})`

**Comment by qgustavor** [comment]
You're downloading those in parallel. It opens too many connections to MEGA at the same time. I never tried doing that, but it would cause errors as their server might consider it a DOS attack.

Try again using callbacks:

```javascript
function processLinks () {
  const link = links.shift()
  if (!link) return console.log('finished')
  const file = mega.file(link)
  file.loadAttributes((err, file) => {
    if (err) return console.error(error)
    file.download((err, data) => {
      if (err) return console.error(err)
      // do something with data
      processLinks()
    })
  })
}
processLinks()
```

**Comment by JoelSParker** [comment]
That worked perfectly! Thank you for your help and this amazing SDK!
