### ISSUE TITLE
How close session ?

### ISSUE THREAD

**Issue by siftmash** [qgustavor/mega#54]
How can I logout and close session. I tried function storage.close() and storage.api.close() but it isn't working. In mega panel -> settings -> history session I see still active session.

**Comment by qgustavor** [comment]
The `storage.close` function was implemented [seven years ago](https://github.com/tonistiigi/mega/commit/42e62712901de5c9be53abb290ac62d3da7f3922), the session feature [was implemented three years ago](https://github.com/meganz/webclient/commit/a11a2e542765fe8cc925d26711d9b6197ed7862b#diff-324a9da285ea75bde09180325631044eR746). In the meanwhile no one bothered to implement session logout into the `Storage` class.

As you can see from the above commit you just need to call `storage.api.request({a: 'sml'}, callback)`. Implementing it is easy as adding a `logout` method to the `Storage` class with the code above.

If you need it you can send a pull request. Please remember to run `npm test` before commiting to check the code against common issues (it will not check if the `.logout()` method works unless you add a test case [here](https://github.com/qgustavor/mega/blob/master/test/storage.test.js) and implement this feature in the [testing server](https://github.com/qgustavor/mega-mock)).
