### ISSUE TITLE
Support login when downloading

### ISSUE THREAD

**Issue by tnp0** [qgustavor/mega#55]
Do you have plans to support 'premium' accounts when downloading?

Mega's daily transfer limits in some regions is quite low, making using it for any kind of retrievable storage very unappealing without a premium account, or completely impossible if you need to download a file larger than a few GB.

For uploads I'm using your library, however for downloads I'm having to call megatools which supports logged in downloads, but unfortunately doesn't support parallel chunk downloading like your library, making it very slow when you get an overloaded file server.

Cheers.

**Comment by qgustavor** [comment]
It's hard to implement as I don't have a premium account. Maybe it will work if you do like this:

```javascript
// Login to MEGA
const storage = new Storage({ ... })
// Open shared file
file = File.fromURL('https://mega.nz/...')
// Replace non-logged API instance with logged API instance
file.api = storage.api
```

I can check MEGA or megatools source-code then try to implement based on what I find on those, but I can't test and, most important, currently don't have time to work in this project. By the way, you can send a pull request.

**Comment by tnp0** [comment]
> ```js
> // Login to MEGA
> const storage = new Storage({ ... })
> // Open shared file
> const file = File.fromURL('https://mega.nz/...')
> // Replace non-logged API instance with logged API instance
> file.api = storage.api
> ```
This appears to be working fine, thanks very much.

> I can check MEGA or megatools source-code then try to implement based on what I find on those, but I can't test and, most important, currently don't have time to work in this project. By the way, you can send a pull request.

This isn't my area so I wouldn't be able to contribute a PR. However, if/when you need a premium account for any testing I'm more than happy to lend you mine.

**Comment by qgustavor** [comment]
As it worked then it's simple: adding a new method to Storage or File seems overkill, just adding this example [to the wiki](https://github.com/qgustavor/mega/wiki/Recipes) will do it.

**Comment by oddwizard** [comment]
Sadly, this doesn't seem to work any more.

**Comment by oddwizard** [comment]
~~Sadly this does not work any more.~~
I was wrong, it still works! 🎉

You have to make sure that `.api` is also *recursively* overwritten for *all children* and that the recursion happens *after* `.loadAttributes()`.


> just adding this example [to the wiki](https://github.com/qgustavor/mega/wiki/Recipes)

Also, the git wiki moved. I couldn't find this trick on mega.js.org. Has it been dropped or am I as blind as I am in finding my own bugs?

**Comment by qgustavor** [comment]
"Files created with new File and File.fromURL by default use a non-logged API instance and can be quite limited. To workaround those limits accounts can be used, so downloading will use the limits from those:"
 https://mega.js.org/docs/1.0/tutorial/network-settings#:~:text=Files%20created%20with%20new%20File%20and%20File.fromURL%20by%20default%20use%20a%20non%2Dlogged%20API%20instance%20and%20can%20be%20quite%20limited.%20To%20workaround%20those%20limits%20accounts%20can%20be%20used%2C%20so%20downloading%20will%20use%20the%20limits%20from%20those%3A

Since it's needed to add it to files recursively the API could be improved.
