### ISSUE TITLE
Attributes could not be decrypted with provided key.

### ISSUE THREAD

**Issue by wiedymi** [qgustavor/mega#58]
Can not login to my account. 
The account has a lot of contacts and shared folders.

```Error: Attributes could not be decrypted with provided key.
    at Function.unpackAttributes (C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:1420:13)
    at MutableFile.decryptAttributes (C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:1097:15)
    at MutableFile.loadMetadata (C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:1089:12)
    at new MutableFile (C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:1487:12)
    at Storage._importFile (C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:2387:38)
    at C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:2326:39
    at Array.forEach (<anonymous>)
    at C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:2326:18
    at Request._callback (C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js:988:7)
    at Request.self.callback (C:\Users\wiedy\Desktop\mega\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (C:\Users\wiedy\Desktop\mega\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Gunzip.<anonymous> (C:\Users\wiedy\Desktop\mega\node_modules\request\request.js:1076:12)```

**Comment by qgustavor** [comment]
This error should only happen when logging-in if some client corrupted you account data. Can you access you account on https://mega.nz?

**Comment by wiedymi** [comment]
> This error should only happen when logging-in if some client corrupted your account data. Can you access your account on https://mega.nz?

Yes, I can.

**Comment by qgustavor** [comment]
I'll check that. As the URL format changed (#57) it's possible that other things were changed too.

**Comment by wiedymi** [comment]
If some file is corrupted, I would prefer to skip it instead of failing the whole process.

**Comment by wiedymi** [comment]
When the changes with a new URL format will be available in packager?

**Comment by qgustavor** [comment]
> If some file is corrupted, I would prefer to skip it instead of failing the whole process.

Replacing [this line](https://github.com/qgustavor/mega/blob/30f5588f4ccfae832954052b782088777859a817/lib/file.js#L405) with `return null` and adding a try catch around the `JSON.parse` would solve this problem, although it can be a breaking change.

> When the changes with a new URL format will be available in packager?

It's available since [this](https://github.com/qgustavor/mega/pull/57#issuecomment-609418631).

**Comment by wiedymi** [comment]
The update did not fix my issue.

```K�>N�.�4q���������Hg�*n�4T╗6�}
K�>N�.�4q���������Hg�*n�4T╗6�} Attributes could not be decrypted with provided key.
```

**Comment by qgustavor** [comment]
> The update did not fix my issue.

The update only changes URL handling, not attribute handling.

I just got into a test account and it worked fine. Edit `C:\Users\wiedy\Desktop\mega\node_modules\megajs\dist\main.node-cjs.js` adding a `console.log('DEBUG:', at)` (or something similar you can debug) before [this line](https://github.com/qgustavor/mega/blob/30f5588f4ccfae832954052b782088777859a817/lib/file.js#L405).

I think the value of `at` for you will be garbled. If MEGA changed how attributes were stored the test I just did would fail. You can also try to make it ignore the error, by changing the `throw` line with `return null`. Do you used any client beside the official ones and this one?

**Comment by wiedymi** [comment]
`Return null` will case the errors.

**Comment by wiedymi** [comment]
```

  static unpackAttributes(at) {
    // read until the first null byte
    let end = 0;
  
    while (end < at.length && at.readUInt8(end)) end++;

    at = at.slice(0, end).toString();

    if (at.substr(0, 6) !== 'MEGA{"') {
      return null
    }
    try {
      return JSON.parse(at.substr(4));
    } catch (error) {
      return null
    }
  }
```


```
  decryptAttributes(at) {
    if (!this.key) return this;
    at = d64(at);
    getCipher(this.key).decryptCBC(at);
    at = File.unpackAttributes(at);
    if (at) {
      this.parseAttributes(at)
    }

    return this;
  }
```
in _importFile
``` 
        if (!parent) {
          parent = {}
          file.parent = parent;
        } else {
          if (!parent.children) parent.children = [];
          parent.children.push(file);
          file.parent = parent;
        }
```

**Comment by wiedymi** [comment]
This code about fixed my issue. Could you please check it and create an update with that?

**Comment by qgustavor** [comment]
Changing `unpackAttributes` like that will ignore the errors. In the other hand why you changed `_importFile`?

**Comment by wiedymi** [comment]
Because parent is undefined in this case and cased an error.

**Comment by qgustavor** [comment]
I will release a fix for those things. It will be a breaking change so it will be a minor version.
