### ISSUE TITLE
Upload to folder

### ISSUE THREAD

**Issue by EdwinAlmendras** [qgustavor/mega#62]
How to upload to folder
Im trying this but dont works

```
storage.root.myfolder.upload(name, data)

```

**Comment by qgustavor** [comment]
From [the wiki](https://github.com/qgustavor/mega/wiki/File#properties): "`children` - Array of files for directories."

Use `storage.root.children.find(node => e.name === 'myfolder').upload(name, data)`

**Comment by Don-Cryptus** [comment]
> From [the wiki](https://github.com/qgustavor/mega/wiki/File#properties): "`children` - Array of files for directories."
> 
> Use `storage.root.children.find(node => e.name === 'myfolder').upload(name, data)`

how would you upload to folder and return the download link in the same context?

**Comment by qgustavor** [comment]
Well, this issue is from 2020, the version 1.0 got released and now easier to use since it now supports promises. The new documentation [is here](https://mega.js.org/) and have a lot of examples. What you are trying to do is something like this:

```
import { Storage } from 'megajs'

const storage = await new Storage({
  email: 'user@example.com',
  password: 'correct horse battery example'
}).ready

const file = await storage.upload('hello-world.txt', 'Hello world!').complete
const link = await file.link()
console.log('The file was uploaded!', link)
```
