### ISSUE TITLE
How to download a range?

### ISSUE THREAD

**Issue by voxsoftware** [qgustavor/mega#63]
I want know, or get an example how to download by range (Partial download) ?

**Comment by qgustavor** [comment]
Use `start` and `end` options when calling `.download()`.

Check [the wiki](https://github.com/qgustavor/mega/wiki/File#downloadoptions-callback), [this recipe](https://github.com/qgustavor/mega/wiki/Recipes#resuming-a-download) and how it was implemented in [direct-mega](https://github.com/qgustavor/direct-mega/blob/8897b53f2e547dd0948cb4923a7c1ed51ebaf3b6/src/sw.js#L222-L227) and [megajs-cli](https://github.com/qgustavor/megajs-cli/blob/3113e7cb05d360fc0c9bfa3c204fdaa554c4ae28/lib/util.js#L94-L97).
