### ISSUE TITLE
WTF is even this shit.

### ISSUE THREAD

**Issue by Temporaly001** [qgustavor/mega#69]
Like is really so hard create a normal documentation with login examples. How the fuck I can login in this shit with email and password. How to find file by name. How to delete file. How to upload file.

**Comment by qgustavor** [comment]
Be respectful, please. Documentation is [in the wiki](https://github.com/qgustavor/mega/wiki). There is an example [in Codepen](https://codepen.io/qgustavor/pen/YNPPqv?editors=0012). An example implementation [is here](https://github.com/qgustavor/megajs-cli/). You can find [projects that use this library here](https://github.com/qgustavor/mega/network/dependents). The usage is almost the same [as this demo](http://tonistiigi.github.io/mega/) (the only change is that `mega.storage({ ... })` was renamed to `mega({ ... })`).
