### ISSUE TITLE
Upload and get download link

### ISSUE THREAD

**Issue by agustinz97** [qgustavor/mega#70]
Is it possible to upload a file and then create and get a download link to share?

**Comment by qgustavor** [comment]
Login like shown [in this demo](http://tonistiigi.github.io/mega/) ([more info here](https://github.com/qgustavor/mega/wiki/Storage)). Upload like shown in this same demo ([more info here](https://github.com/qgustavor/mega/wiki/MutableFile#uploadoptions--name-data-callback)). To get the share link just call `.link(callback)` on the uploaded file ([more info here](https://github.com/qgustavor/mega/wiki/MutableFile#linkoptions-callback--sharefolderoptions-callback)).
