### ISSUE TITLE
EAGAIN (-3): A temporary congestion or server malfunction prevented your request from being processed. No data was altered. Retried 4 times.

### ISSUE THREAD

**Issue by wiedymi** [qgustavor/mega#73]
`EAGAIN (-3): A temporary congestion or server malfunction prevented your request from being processed. No data was altered. Retried 4 times.`

How to fix this error?
I just create folders...

**Comment by qgustavor** [comment]
Creating folder is documented here: https://github.com/qgustavor/mega/wiki/MutableFile#mkdiroptions--name-callback

Sample code:

```javascript
import { Storage } from 'megajs'
const { MEGA_EMAIL, MEGA_PASSWORD } = process.env
const storage = new mega.Storage({
  email: MEGA_EMAIL,
  password: MEGA_PASSWORD
})
storage.once('ready', () => {
  storage.root.mkdir('name of the folder', (error, folder) => {
    // handle error or do something with folder
  })
})
```

About the error: as it says it's just a *temporary* server issue, so it's outside your control. Just be sure you're using callbacks correctly and not submitting too many requests to the server in a small period of time (which may congest the server).
