### ISSUE TITLE
Can't browse folder inside a shared folder

### ISSUE THREAD

**Issue by kbzowski** [qgustavor/mega#77]
I am trying to loadAttributes directly about the shared subfolder via the link:
https://mega.nz/folder/{DIRECTORY}#{KEY}
The key is in the format: {KEY}/folder/S5tHUYJK

This throws an exception: Invalid argument {KEY}/folder/S5tHUYJK

How can I list files in subfolder directly?

**Comment by kbzowski** [comment]
This was as simple as connect to parent folder and:
```
file.loadAttributes((error, folder) => {
        const file= folder.children[2].children[2].children[0];
        file.download().pipe(fs.createWriteStream('myfile.rar'))
})
```

**Comment by qgustavor** [comment]
Seems URL parsing is not implemented correctly for folders. You can fix [those lines](https://github.com/qgustavor/mega/blob/a627db06be2d6d88ebac99906ee4340bc3a339d2/lib/file.js#L367-L383) and submit a pull request. I think replacing `.split('/file/')` with `.split(/\/(file|folder)\//)` would be a simple solution but a better one would be checking MEGA's code for that and reimplementing it
