### ISSUE TITLE
mega server wait req failed

### ISSUE THREAD

**Issue by timvol** [qgustavor/mega#79]
I'm often getting the following error:

```
/home/node/node_modules/megajs/dist/main.node-cjs.js:1104
      if (err) throw Error('mega server wait req failed');
```

Any idea how I can fix this or why it happens?

Sometimes also the download of some files simply doesn't start.

**Comment by qgustavor** [comment]
That's issue #47. [The code that throws this error](https://github.com/qgustavor/mega/blob/a627db06be2d6d88ebac99906ee4340bc3a339d2/lib/api.js#L115-L125) is almost the same [as the original library](https://github.com/tonistiigi/mega/blob/eb2c8fc639ee7affb3c3d4811bad200c7d4d8a92/lib/api.js#L118-L130). I don't know how to solve, I just rewrote this part of the code to use modern JavaScript, but the functionally is the same.

A hacky "fix" for this I did once was editing main.node-cjs.js with the following code:

```javascript
  wait(url$$1, sn, errors = 0) {
    this.sn = this.requestModule({
      uri: url$$1,
      method: 'POST'
    }, (err, req, body) => {
      this.sn = undefined;
      if (err) {
        // this.emit('error', Error('mega server wait req failed'));
        setTimeout(() => {
          this.wait(url$$1, sn, errors + 1)
        }, Math.pow(2, errors) * 30e3)
        return
      }
      this.pull(sn);
    });
  }
```

I don't know if this fix is good or not, it's just a hack, so it's not implemented in the library. If you think you can find a better fix for this issue send a pull request. I will close this issue in favor of #47.
