### ISSUE TITLE
don't throw error on empty file

### ISSUE THREAD

**Issue by Myriad-Dreamin** [qgustavor/mega#83]
If the `response.s` equals zero, `end` will be assigned to `-1`, making the code fail the check on line 231.

```typescript
if (response.s === 0) {
  stream.emit('end'); // return without emitting error event
  return;
}
```

https://github.com/qgustavor/mega/blob/a627db06be2d6d88ebac99906ee4340bc3a339d2/lib/file.js#L224-L233

**Comment by qgustavor** [comment]
I think setting `{end: 0}` will omit this error, but what is a good way to solve this? Well, we all know that if `response.s === 0` then we can just call `return stream.end()` and call it a day, no?
